# site settings
title: Vaishak Prasad
subtitle: Personal and resources site
email: vaishakprasad@gmail.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/massively-jekyll-theme" # the subpath of your site, e.g. /blog
url: "vaishakp.github.io" # the base hostname & protocol for your site
author: Vaishak Prasad
street_address: 251 Pollock Rd, University Park
city: State College
state: PA
zip_code: 16802
country: United States of America
phone:

# social settings
500px_url:
facebook_url:
github_url: https://github.com/vaishakp
gitlab_url: https://gitlab.com/u/vaishakp
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/vaishakp

# build settings
markdown: kramdown

sass:
  style: compressed
